name: Pylint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Analysing the code with pylint
      run: |
        pylint `find . -path ./cookiecutter -prune -false -o -name "*.py"` --rcfile=.pylintrc
    - name: Testing code with pytest
      run: |
        pytest --ignore=cookiecutter/\{\{\ cookiecutter.repo_name\ \}\}/src/test_code.py
